
#/invite.html           https://discord.com/api/oauth2/authorize?client_id=721460877005422634&permissions=1392039259222&scope=bot%20applications.commands
[[redirects]]
from = "/invite"
to = "https://discord.com/api/oauth2/authorize?client_id=721460877005422634&permissions=1392039259222&scope=bot%20applications.commands"
status = 200
force = true

[[redirects]]
from = "/invite.html"
to = "https://discord.com/api/oauth2/authorize?client_id=721460877005422634&permissions=1392039259222&scope=bot%20applications.commands"
status = 200
force = true

[[redirects]]
from = "/pages/*"
to = "/*"
status = 200
force = true

# Role-based redirects do not have a “to” property.
#/* /error.html 404
[[redirects]]
from = "/*"
to = "/error.html"
status = 404