# Role-based redirects do not have a “to” property.
#/* /error.html 404
[[redirects]]
to = "/error.html"
status = 404
force = true

#/invite.html           https://discord.com/api/oauth2/authorize?client_id=721460877005422634&permissions=1392039259222&scope=bot%20applications.commands
[[redirects]]
from = "/invite.html"
to = "https://discord.com/api/oauth2/authorize?client_id=721460877005422634&permissions=1392039259222&scope=bot%20applications.commands"
force = true
